### ISSUE TITLE
Friction issue for small bodies

### ISSUE THREAD

**Issue by liabru** [liabru/matter-js#169]
via @Lange: Small bodies have some strange issues with friction, see https://jsfiddle.net/liabru/ohfqrqqj/. The larger body has the same vertices, but appears to be much more stable, although can still exhibit similar issues to a much lesser extent.

**Comment by Richacinas** [comment]
+1

I'm having the same issues on a sort of a lottery machine where I have like a 100 small bodies. They shake a lot even when there is no movement at all.

**Comment by liabru** [comment]
This should now be resolved in the latest master build, please tell me how you get on.

**Comment by Richacinas** [comment]
Hi liabru, sorry for not answering before. We already have this project on production and at the moment we are not going to release new changes. 

I'm sure we will use it again, I think it works very well and the documentation is very helpful too.

I will write again when we notice some improvements relating to this issue. Thanks a lot

**Comment by liabru** [comment]
No problem! Is there a link to it?

**Comment by pacmanmulet** [comment]
this issue it is still not fixed: https://jsfiddle.net/mqn1djj2/
Look work different when create the body inside/out worl.add() function

**Comment by liabru** [comment]
@pacmanmulet I took a look, the reason is because the `walld` object only has a height of `1` which is too thin for collisions to resolve properly. If you make the height `5` for example, it seems to work fine. I would suggest making the height as large as possible to prevent issues though (at least until #5 has been merged).
